feat: adds path to tempoit config for mac users
swalladge/tempoit pull request #3
Opened 2021-08-11 18:27 UTC by nizarmah

I recently had to install this script on a Mac. Unfortunately, I kept running into issues with the login. 

After some investigation, it turns out that `confy`, which is the package used to serialize and deserialize the `tempoit.toml` config, uses `directories` to locate the configuration file path.

According to the [`directories` docs](https://crates.io/crates/directories), the `preference_dir`, which is `$HOME/.config` on Linux, is `$HOME/Library/Preferences` on Mac and `{FOLDERID_RoamingAppData}` on Windows.

However, it's important to note that this will not remain the case with `confy = 0.5.0' due to a [breaking change](https://github.com/rust-cli/confy/blob/664992aecd97b4af0eda8d9d2825885662e1c6b4/README.md#version-050). The breaking change is that `confy` switched from `directories` to `directories-next` because the former is no longer maintained.

Accordingly, in the future, once `confy = 0.5.0` is available on cargo, the README should be updated again to the `config_dir` mentioned on the [`directories-next` docs](https://crates.io/crates/directories-next). Although the config location on windows will remain the same, on Mac it will become `$HOME/Library/Application Support`. 

---

If you don't like to mention the path of the config for Mac, I can make a change to link to the docs mentioned earlier. It would immensely help anyone who hasn't touched rust, ever, like myself 😛

2021-08-12 21:26 UTC, swalladge requested changes
@nizarmah thanks for this!  I added a suggestion, but otherwise I agree that adding this would be helpful.

> feat: adds

I'm not sure this is a 'feature'.  Would you mind dropping the 'conventional commits', and instead use the standard [imperative mood](https://chris.beams.io/posts/git-commit/#imperative) in the title, and add the 'why' (ie. your PR description) to the body of the commit?

2021-08-12 21:26 UTC, swalladge commented on README.md
> +
To be consistent, could you document the directory location on all three major platforms, as you mentioned in the PR?  I'm thinking a bulleted list maybe?

2021-08-13 08:54 UTC, nizarmah commented
@swalladge not going to lie, I prefer the [imperative mood](https://chris.beams.io/posts/git-commit/#imperative) much more than conventional commits! Thanks a lot for linking that 😃 

I'll update my commit once #4 is merged 👍🏼 I'll also link to the `directories-next` `config_dir` table row instead of mentioning the value explicitly.

2021-08-13 08:56 UTC, nizarmah commented on README.md
> +
Sounds good 👍🏼 I was thinking of updating the change to link to `directories-next` and to mention that it is the `config_dir` row, where people can check the path that corresponds to their machine. However, I'll mention them as a bulleted list, as you requested 😃

2021-08-13 11:19 UTC, swalladge commented on README.md
> +
> I was thinking of updating the change to link to directories-next and to mention that it is the config_dir row, where people can check the path that corresponds to their machine.

I don't mind, whichever you think will be more usable :D 

Thanks for for taking the time to document this all, I really appreciate it!

2021-08-14 14:07 UTC, nizarmah commented
https://github.com/xdg-rs/dirs/blob/af4aa39daba0ac68e222962a5aca17360158b7cc/directories/README.md#L101

2021-08-14 14:28 UTC, nizarmah commented
@swalladge I've updated the commit 👍🏼 I'll keep an eye when you merge the update confy dependency pull request, in case there's any conflicts 😄

2021-08-14 21:28 UTC, swalladge approved these changes

2021-08-14 21:29 UTC, merged

2021-08-14 21:29 UTC, swalladge commented
@nizarmah thanks, merged everything! :D

2021-08-14 21:31 UTC, swalladge commented
btw, I'm moving this repository to https://git.sr.ht/~swalladge/tempoit now; I've been moving all my repos off github.  :)